apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
    app: mongo-pod
spec:
  selector:
    name: mongo-pod
    app: mongo-pod
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

