apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    name: ui-service
    app: loan-predictor
spec:
  selector:
    name: ui-pod
    app: loan-predictor
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer

