apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    app: loan-predictor
spec:
  selector:
    name: redis-pod
    app: loan-predictor
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

