apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    name: server-service
    app: loan-predictor
spec:
  selector:
    name: server-pod
    app: loan-predictor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
      

